### PR TITLE
add doc for elastic energy and its derivatives

### PR DESCRIPTION
**Pull request by zeshunzong**
This change is [Reviewable](https://reviewable.io/reviews/zeshunzong/drake/27)

### CODE REVIEW

**Review by zeshunzong — COMMENTED** [review]
+@xuchenhan-tri  Remember, ctrl + shift + v to preview markdown in VScode

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/27#-:-Nn5RMx7AjMmcdcyiTTZ:b-ysbz47)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by xuchen-han — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/27#-:-NnAbElRB79GfSaLh7hj:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/doc/energy_derivatives.md` line 1 at r1](https://reviewable.io/reviews/zeshunzong/drake/27#-NnAa0gR2_CJMwLF-6kt:-NnAa0gR2_CJMwLF-6ku:bunsz9k) ([raw file](https://github.com/zeshunzong/drake/blob/21539edf326a00826bfba55d78a1cc68a5d3d12a/multibody/mpm/doc/energy_derivatives.md#L1)):*
> ```Markdown
> ## Elastic energy and its derivatives
> ```

btw, this is fine as is for now. But eventually, we should have a overview doc that explains the entire Newton algorithm with this energy derivative/hessian as a subsection.
___
*[`multibody/mpm/doc/energy_derivatives.md` line 27 at r1](https://reviewable.io/reviews/zeshunzong/drake/27#-NnAaHyQ8Cxpz6DlnAXF:-NnAaHyQ8Cxpz6DlnAXG:b-cq2ufb) ([raw file](https://github.com/zeshunzong/drake/blob/21539edf326a00826bfba55d78a1cc68a5d3d12a/multibody/mpm/doc/energy_derivatives.md#L27)):*
> ```Markdown
> 
> We can also compute the product of the hessian $H(x^*)(i\alpha, j\rho)$ with an arbitrary vector $z$, which is of length 3 * number of nodes. The result is 
> $$y_i = (Hz)[3i:3i+3] = \sum_p V_p^0 A_p {(F^0_p)}^T \nabla N_i(x_p^0),$$
> ```

nit, this was slightly confusing to me on first read. I thought you were transposing A. Consider



_Suggestion:_
```Markdown
$$y_i = (Hz)[3i:3i+3] = \sum_p V_p^0 A_p(F(x^*)) (F^0_p)^T \nabla N_i(x_p^0),$$
```

**Review by xuchen-han — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/27#-:-NnAbHZk3R-LRoDecsTb:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @zeshunzong)

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/27)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

___
*[`multibody/mpm/doc/energy_derivatives.md` line 27 at r1](https://reviewable.io/reviews/zeshunzong/drake/27#-NnAaHyQ8Cxpz6DlnAXF:-NnAzNTi6bi7zwQTU0A3:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/21539edf326a00826bfba55d78a1cc68a5d3d12a/multibody/mpm/doc/energy_derivatives.md#L27)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, this was slightly confusing to me on first read. I thought you were transposing A. Consider
</blockquote></details>

done

**Review by xuchen-han — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/27)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

**Pull request merged**
