### PR TITLE
add grid data and some empty files

### PR DESCRIPTION
**Pull request by zeshunzong**
This change is [Reviewable](https://reviewable.io/reviews/zeshunzong/drake/23)

### CODE REVIEW

**Review by zeshunzong — COMMENTED** [review]
+@xuchenhan-tri  another light PR

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/23#-:-NjjVGKq4cMMkt4zK1vj:bs9afpz)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by xuchen-han — CHANGES_REQUESTED** [review]
:lgtm: with a few minor comments.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/23#-:-NjjjQENCf5rUOaEWhIN:bavmcyl)* status: all files reviewed, 6 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/grid_data.h` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjilTjAZVfsu3sCe4A:-NjjilTjAZVfsu3sCe4B:b661hyi) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L11)):*
> ```objc
> namespace drake {
> namespace multibody {
> namespace mpm {
> ```

BTW, why is this class not in the internal namespace?
___
*[`multibody/mpm/grid_data.h` line 55 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-Njji_USBM1ZSTvnsHDa:-Njji_UTEzKGgYfLMs9A:b84y7qd) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L55)):*
> ```objc
>    */
>   void AccumulateAt(
>       size_t index_1d,
> ```

nit bound check the index with DRAKE_DEMAND or DRAKE_ASSERT.
___
*[`multibody/mpm/grid_data.h` line 56 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjiEExCDh-0matDOwa:-NjjiEExCDh-0matDOwb:bzcpicw) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L56)):*
> ```objc
>   void AccumulateAt(
>       size_t index_1d,
>       const std::tuple<T, Vector3<T>, Vector3<T>>& mass_momentum_force) {
> ```

nit why std::tuple over a struct or three individual arguments?

FYI https://drake.mit.edu/styleguide/cppguide.html#Structs_vs._Tuples
___
*[`multibody/mpm/grid_data.h` line 57 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjiTxwE0UFSj4cHHsn:-NjjiTxwE0UFSj4cHHso:b-8z2kig) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L57)):*
> ```objc
>       size_t index_1d,
>       const std::tuple<T, Vector3<T>, Vector3<T>>& mass_momentum_force) {
>     const auto [mass, momentum, force] = mass_momentum_force;
> ```

BTW you are making an unnecessary copy here.
___
*[`multibody/mpm/grid_data.h` line 66 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-Njjj7owAIrWCScLfesK:-Njjj7owAIrWCScLfesL:bodkep3) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L66)):*
> ```objc
>    * Computes the velocity for momentum for each active grid node.
>    * @pre masses_[i] > 0 for all i. This will be satisfied if only active grid
>    * nodes are stored and mass has already been accumulated.
> ```

nit, I think it'd be more accurate to say 



_Suggestion:_
```objc
and grid data for each active grid node has been accumulated.
```
___
*[`multibody/mpm/mpm_transfer.h` line 12 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjjVf--5raCeobrVOu:-NjjjVf--5raCeobrVOv:b-ppzerz) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/mpm_transfer.h#L12)):*
> ```objc
> namespace drake {
> namespace multibody {
> namespace mpm {
> ```

nit why is this class not in internal namespace?

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/23)* status: all files reviewed, 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/grid_data.h` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjilTjAZVfsu3sCe4A:-NjjkrxM-284s5N0NEiw:bs84oqu) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L11)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, why is this class not in the internal namespace?
</blockquote></details>

why internal? this is the most important chuck of data we need. This is at least as important as, if not more important than the particles data.
___
*[`multibody/mpm/grid_data.h` line 56 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjiEExCDh-0matDOwa:-Njjlj_HBOYb0f-hevTB:b-2snhyd) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L56)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit why std::tuple over a struct or three individual arguments?

FYI https://drake.mit.edu/styleguide/cppguide.html#Structs_vs._Tuples
</blockquote></details>

ah I did not know that. Then why in B-spline we can do [w, dw] = ... which is a pair? BTW I think this is a very limited use-case and will not be used elsewhere.
___
*[`multibody/mpm/mpm_transfer.h` line 12 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjjVf--5raCeobrVOu:-NjjlAMP4Szbny-_fhpj:bi7ru9e) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/mpm_transfer.h#L12)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit why is this class not in internal namespace?
</blockquote></details>

why internal? this should be exposed to everyone. Say without deformable driver or so this should still be a standalone MPM

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/23)* status: all files reviewed, 4 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/grid_data.h` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjilTjAZVfsu3sCe4A:-Njk4rsaEzDyQIomQSXq:b-bshtvf) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L11)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

why internal? this is the most important chuck of data we need. This is at least as important as, if not more important than the particles data.
</blockquote></details>

just to add one more, I think GridData, SparseGrid, Particles, MPMtransfer are equivalently important components and should be all under mpm namespace
___
*[`multibody/mpm/grid_data.h` line 55 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-Njji_USBM1ZSTvnsHDa:-Njk2Z7o2eoUX1Sbw084:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L55)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit bound check the index with DRAKE_DEMAND or DRAKE_ASSERT.
</blockquote></details>

done
___
*[`multibody/mpm/grid_data.h` line 57 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjiTxwE0UFSj4cHHsn:-Njk4Jh-Dc7H-NYNCQtM:bw8hlrv) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L57)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW you are making an unnecessary copy here.
</blockquote></details>

I changed to three individual arguments. But basically I don't want to write three getters.

T GetMassAt(a, b, c) {
index = 27*a+9*b+c; return masses[index];
}
Vec GetMomentum(a, b, c) ...

But intead GetTuple() {return {.., .., ..}}
___
*[`multibody/mpm/grid_data.h` line 66 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-Njjj7owAIrWCScLfesK:-Njk3yUL9MbrHxcrcB1d:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L66)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, I think it'd be more accurate to say
</blockquote></details>

done
___
*[`multibody/mpm/mpm_transfer.h` line 12 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjjVf--5raCeobrVOu:-Njk40a97L_cL_EyRzlU:b-gt3jkq) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/mpm_transfer.h#L12)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

why internal? this should be exposed to everyone. Say without deformable driver or so this should still be a standalone MPM
</blockquote></details>

Just to add one more. I don't think P2G and something like math_util::exponential() should be put at the same level

**Review by xuchen-han — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/23)* status: all files reviewed, 3 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/grid_data.h` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjilTjAZVfsu3sCe4A:-Njn1D8F8E89JGX6bm8Q:b-ldks0b) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L11)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

just to add one more, I think GridData, SparseGrid, Particles, MPMtransfer are equivalently important components and should be all under mpm namespace
</blockquote></details>

The functional importance of a piece of code is irrelevant to whether the class is internal or not. The code be should be internal if it's not end user facing.

Note that `DeformableDriver` is in the internal namespace. If the sole consumer of `GridData` is `DeformableDriver`, then `GridData` should be internal too.
___
*[`multibody/mpm/grid_data.h` line 56 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjiEExCDh-0matDOwa:-Njn2KZX0UNxn4d09XDk:bqgqgjg) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L56)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

ah I did not know that. Then why in B-spline we can do [w, dw] = ... which is a pair? BTW I think this is a very limited use-case and will not be used elsewhere.
</blockquote></details>

I think the [w, dw] pair is pretty clear. A 3-tuple is pushing it a bit.
___
*[`multibody/mpm/grid_data.h` line 57 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjiTxwE0UFSj4cHHsn:-Njn3P-9DqvpYk1h_D9F:b-lzplot) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L57)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

I changed to three individual arguments. But basically I don't want to write three getters.

T GetMassAt(a, b, c) {
index = 27*a+9*b+c; return masses[index];
}
Vec GetMomentum(a, b, c) ...

But intead GetTuple() {return {.., .., ..}}
</blockquote></details>

The defect here is orthogonal to the use of tuple. You are just missing a reference here.

`const auto& [mass, momentum, force] = mass_momentum_force;` is enough
___
*[`multibody/mpm/mpm_transfer.h` line 12 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjjVf--5raCeobrVOu:-Njn3cXG7lZvimNAyFUc:b-hxr962) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/mpm_transfer.h#L12)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

Just to add one more. I don't think P2G and something like math_util::exponential() should be put at the same level
</blockquote></details>

See the discussion of internal vs public above.

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

___
*[`multibody/mpm/grid_data.h` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjilTjAZVfsu3sCe4A:-NjnAPloBdduOOd6RHPj:b-apscoz) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L11)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The functional importance of a piece of code is irrelevant to whether the class is internal or not. The code be should be internal if it's not end user facing.

Note that `DeformableDriver` is in the internal namespace. If the sole consumer of `GridData` is `DeformableDriver`, then `GridData` should be internal too.
</blockquote></details>

done acknowledged. postpone to a later stage
___
*[`multibody/mpm/grid_data.h` line 56 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjiEExCDh-0matDOwa:-NjnAUzp4H8rHijiSGIW:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L56)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I think the [w, dw] pair is pretty clear. A 3-tuple is pushing it a bit.
</blockquote></details>

done
___
*[`multibody/mpm/grid_data.h` line 57 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjiTxwE0UFSj4cHHsn:-NjnAVgYA-PSKFr4e-2P:b8lzn86) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/grid_data.h#L57)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The defect here is orthogonal to the use of tuple. You are just missing a reference here.

`const auto& [mass, momentum, force] = mass_momentum_force;` is enough
</blockquote></details>

done I was aware of that, that was a typo.
___
*[`multibody/mpm/mpm_transfer.h` line 12 at r1](https://reviewable.io/reviews/zeshunzong/drake/23#-NjjjVf--5raCeobrVOu:-NjnApvGBxYlDYhvuf1I:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/bd0dfcb49e9b5ece83f27b5f70aa64353c148a00/multibody/mpm/mpm_transfer.h#L12)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

See the discussion of internal vs public above.
</blockquote></details>

done

**Review by xuchen-han — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

**Pull request merged**
