### PR TITLE
add g2p

### PR DESCRIPTION
**Pull request by zeshunzong**
This change is [Reviewable](https://reviewable.io/reviews/zeshunzong/drake/26)

### CODE REVIEW

**Comment by zeshunzong** [comment]
+@xuchenhan-tri Not sure if this is the best way. Some stuff are put under particles.h, and some are put under transfer.h. I manage to have that particles.h does not include sparse_grid.h, and vice versa (which is what I want).

Not exactly sure all namings are clear, suggestions are welcome

**Review by xuchen-han — CHANGES_REQUESTED** [review]
I made a pass. The main question I have about whether particle advection should be part of G2P.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/26#-:-NkMmaEp-4-yaka5ct42:bqx00ke)* status: all files reviewed, 8 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/interpolation_weights.h` line 130 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMTcwc00a02GxSrZTe:-NkMTcwc00a02GxSrZTf:bb7phvt) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/interpolation_weights.h#L130)):*
> ```objc
>    * Given the grid data on 27 (3by3by3 cube) nodes stored in batch_pad that are
>    * in the support of p-th particle, computes and returns the new velocity, new
>    * B_matri, and new velocity gradient of the p-th particle.
> ```

typo



_Suggestion:_
```objc
 * B_matrix, and new velocity gradient of the p-th particle.
```
___
*[`multibody/mpm/interpolation_weights.h` line 132 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMTsnD31mijTz9Eux9:-NkMTsnD31mijTz9EuxA:byk7sdd) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/interpolation_weights.h#L132)):*
> ```objc
>    * B_matri, and new velocity gradient of the p-th particle.
>    */
>   ParticleVBGradV<T> AccumulateFromBatchPad(const Vector3<T>& x_p,
> ```

nit, there's an undocumented precondition on `x_p` here (that it has to be in the convex hull generated by `batch_pad.positions`).
___
*[`multibody/mpm/interpolation_weights.h` line 148 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMRhiK0xkXC4HpW3zb:-NkMRhiK0xkXC4HpW3zc:bdl1lc2) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/interpolation_weights.h#L148)):*
> ```objc
>           vi_new = pad_velocities[idx_local] * weights_[idx_local];
>           // v_p^{n+1} = \sum v_i^{n+1} N_i(x_p)
>           vp_new += vi_new;
> ```

The code doesn't match the comment. It's a bit confusing to use `vi` to denote weighted grid velocity.
BTW, I don't think the `_new` suffix buy you much. You could have just create a `ParticleVBGradV` object at the beginning of the loop and write over it.
Also it'd be nice to leave a reference to where you can find these equations.



_Code quote:_
```objc
          // v_p^{n+1} = \sum v_i^{n+1} N_i(x_p)
          vp_new += vi_new;
```
___
*[`multibody/mpm/interpolation_weights.h` line 154 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMSjP57BX8Jv9s08lJ:-NkMSjP57BX8Jv9s08lK:b-xbei67) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/interpolation_weights.h#L154)):*
> ```objc
> 
>           // Accumulate grad_vp_new: F_p^{n+1} = (I + dt*grad_vp_new)*F_p^n
>           grad_vp_new += vi_new * weight_gradients_[idx_local].transpose();
> ```

The code doesn't match the comment. We are not updating Fp here.



_Code quote:_
```objc
          // Accumulate grad_vp_new: F_p^{n+1} = (I + dt*grad_vp_new)*F_p^n
          grad_vp_new += vi_new * weight_gradients_[idx_local].transpose();
```
___
*[`multibody/mpm/mpm_transfer.h` line 42 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMREg4DMS56MmsQf-H:-NkMREg4DMS56MmsQf-I:b-3xbmk5) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/mpm_transfer.h#L42)):*
> ```objc
>  * // g2p tbd
>  *
>  * <-- TODO(zeshunzong): this is not complete and not exactly accurate for
> ```

This TODO should be addressed in this PR.
___
*[`multibody/mpm/mpm_transfer.h` line 75 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMU7hK8vEqEROoJufA:-NkMU7hK8vEqEROoJufB:bjmnzlr) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/mpm_transfer.h#L75)):*
> ```objc
>    * Given grid_data, writes to particles.
>    */
>   void G2P(const SparseGrid<T>& grid, const GridData<T>& grid_data, double dt,
> ```

I don't see why `dt` needs to be part of G2P.



_Code quote:_
```objc
 double dt,
```
___
*[`multibody/mpm/mpm_transfer.cc` line 58 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMm4_E2r7LDkThdmuj:-NkMm4_E2r7LDkThdmuk:b-g5x4d8) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/mpm_transfer.cc#L58)):*
> ```cpp
>   }
> 
>   particles->AdvectParticles(dt);
> ```

I wonder if you have considered moving particle advection out of G2P and what the implications are.
___
*[`multibody/mpm/pad.h` line 44 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMQIwT0oKyKT1dQsz2:-NkMQIwUEXIh_WUUIDP6:b-pcxr9o) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/pad.h#L44)):*
> ```objc
> 
> template <typename T>
> struct BatchPad {
> ```

The distinction between `Pad` and `BatchPad` doesn't make sense to me. IIUC, what you have are `P2gPad` and `G2pPad`.

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/26)* status: all files reviewed, 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/interpolation_weights.h` line 130 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMTcwc00a02GxSrZTe:-NkOqv5vBnsRbwwI5ZjF:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/interpolation_weights.h#L130)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

done
___
*[`multibody/mpm/interpolation_weights.h` line 132 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMTsnD31mijTz9Eux9:-NkOr0N87UVkLcY_K6uT:b-a1vetq) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/interpolation_weights.h#L132)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, there's an undocumented precondition on `x_p` here (that it has to be in the convex hull generated by `batch_pad.positions`).
</blockquote></details>

done I added it per your suggestion, but frankly speaking you cannot expect someone to check it.
___
*[`multibody/mpm/interpolation_weights.h` line 148 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMRhiK0xkXC4HpW3zb:-NkOzzJtDV-QjmJTUfhD:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/interpolation_weights.h#L148)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The code doesn't match the comment. It's a bit confusing to use `vi` to denote weighted grid velocity.
BTW, I don't think the `_new` suffix buy you much. You could have just create a `ParticleVBGradV` object at the beginning of the loop and write over it.
Also it'd be nice to leave a reference to where you can find these equations.
</blockquote></details>

done
___
*[`multibody/mpm/interpolation_weights.h` line 154 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMSjP57BX8Jv9s08lJ:-NkP-1nq78hVKjn8-l2_:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/interpolation_weights.h#L154)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The code doesn't match the comment. We are not updating Fp here.
</blockquote></details>

done
___
*[`multibody/mpm/mpm_transfer.h` line 75 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMU7hK8vEqEROoJufA:-NkP-84j3U82--kczInV:brfb46o) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/mpm_transfer.h#L75)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I don't see why `dt` needs to be part of G2P.
</blockquote></details>

Per our discussion today, I think there should still be a debate.

From a pure explicit point of view, after G2P, it should be that particle x, v, C, F are all at the new temporal state. This means that dt should be included for both F update and x update. Technically you don't want things to be out of phase after the call of public function G2P()

From the view of implicit, we want to consider the steps necessary to update energy. I think a separate function that incorporates parts of P2G and G2P (in a copy and paste way) should be designated for this.
___
*[`multibody/mpm/mpm_transfer.cc` line 58 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMm4_E2r7LDkThdmuj:-NkP0ksY5bMF2fAQDSmc:b-ksczw) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/mpm_transfer.cc#L58)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I wonder if you have considered moving particle advection out of G2P and what the implications are.
</blockquote></details>

seee above
___
*[`multibody/mpm/pad.h` line 44 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMQIwT0oKyKT1dQsz2:-NkP0mtYEvG9flkFjPkm:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/pad.h#L44)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The distinction between `Pad` and `BatchPad` doesn't make sense to me. IIUC, what you have are `P2gPad` and `G2pPad`.
</blockquote></details>

done

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/26)* status: 2 of 10 files reviewed, 6 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/mpm_transfer.h` line 42 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMREg4DMS56MmsQf-H:-NkP5ipw1zamC9vAIDz7:byky6hl) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/mpm_transfer.h#L42)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This TODO should be addressed in this PR.
</blockquote></details>

edited a bit. this TODO should be kept until the whole implicit is fixed,

**Review by xuchen-han — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/26)* status: all files reviewed, 2 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/interpolation_weights.h` line 132 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMTsnD31mijTz9Eux9:-NkScgdYB1Q0IDayXnMD:bv609rh) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/interpolation_weights.h#L132)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

done I added it per your suggestion, but frankly speaking you cannot expect someone to check it.
</blockquote></details>

I think it's still nice to have. It leaves some bread crumbs for future developers to debug if something goes wrong.
___
*[`multibody/mpm/interpolation_weights.h` line 139 at r2](https://reviewable.io/reviews/zeshunzong/drake/26#-NkScdWS2RdoD1Dgwwsc:-NkScdWS2RdoD1Dgwwsd:bcluxjz) ([raw file](https://github.com/zeshunzong/drake/blob/a44a923b6e52f097809c29aa094315431d4141a8/multibody/mpm/interpolation_weights.h#L139)):*
> ```objc
>    * B_matrix, and new velocity gradient of the p-th particle.
>    * We
>    * follow the APIC transfer routine in
> ```

BTW weird indent



_Code quote:_
```objc
   * We
   * follow the APIC transfer routine in
```
___
*[`multibody/mpm/mpm_transfer.h` line 75 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMU7hK8vEqEROoJufA:-NkSdNouByC9XQiiNz6H:b-esv029) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/mpm_transfer.h#L75)):*
> From a pure explicit point of view, after G2P, it should be that particle x, v, C, F are all at the new temporal state. This means that dt should be included for both F update and x update. Technically you don't want things to be out of phase after the call of public function G2P()

I'd like to think of G2P as an operation to get v(n+1). It'd be nice if we'd be able to decouple that from the integration scheme used. In my head I'm imgining a separate function that would integrate over time and gives x(n+1) (and its dependents). That would give us the flexibility to do all sorts of integration schemes (symplectic Euler, backward Euler, mid point rule, etc).

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/26)* status: all files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/mpm_transfer.h` line 75 at r1](https://reviewable.io/reviews/zeshunzong/drake/26#-NkMU7hK8vEqEROoJufA:-NkUZwRr-tw55jsjNpbP:bi30odi) ([raw file](https://github.com/zeshunzong/drake/blob/8b79b45b4dbc2b5f29f6811c785abcdf938c4dc9/multibody/mpm/mpm_transfer.h#L75)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> From a pure explicit point of view, after G2P, it should be that particle x, v, C, F are all at the new temporal state. This means that dt should be included for both F update and x update. Technically you don't want things to be out of phase after the call of public function G2P()

I'd like to think of G2P as an operation to get v(n+1). It'd be nice if we'd be able to decouple that from the integration scheme used. In my head I'm imgining a separate function that would integrate over time and gives x(n+1) (and its dependents). That would give us the flexibility to do all sorts of integration schemes (symplectic Euler, backward Euler, mid point rule, etc).
</blockquote></details>

see new version

**Review by xuchen-han — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r3, 2 of 4 files at r4, 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/26#-:-NkrL6RcE2CxCDAOyRtl:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/mpm_solver.h` line 14 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrK6g07HBMJGnVaFlZ:-NkrK6g07HBMJGnVaFl_:b-3rowo8) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/mpm_solver.h#L14)):*
> ```objc
> 
> template <typename T>
> class MpmSolver {};
> ```

nit this should be left for a separate PR.
___
*[`multibody/mpm/mpm_transfer.h` line 30 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrF4Kt8cZOChX0X_Ku:-NkrF4Kt8cZOChX0X_Kv:b-hgjnps) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/mpm_transfer.h#L30)):*
> ```objc
>  * ParticlesData<double> particles_data; -- data holder for particles
>  *
>  * Explicit temporal advancement in psuedo code:
> ```

typo, ditto below.



_Suggestion:_
```objc
Explicit temporal advancement in pseudocode
```
___
*[`multibody/mpm/mpm_transfer.h` line 33 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrGVZJ1rNFM3te-ZzB:-NkrGVZJ1rNFM3te-ZzC:bb7phvt) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/mpm_transfer.h#L33)):*
> ```objc
>  * In: Pₙ particles at tₙ
>  * Out: Gₙ₊₁ grid state at tₙ₊₁, Pₙ₊₁ particles at tₙ₊₁.
>  * SetupTranfer(Pₙ, ...)
> ```

typo



_Suggestion:_
```objc
SetupTransfer(Pₙ, ...)
```
___
*[`multibody/mpm/mpm_transfer.h` line 48 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrGahN0Dh-y0IBVQP9:-NkrGahN0Dh-y0IBVQPA:b-rs4as1) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/mpm_transfer.h#L48)):*
> ```objc
>  * while |dG|>ε:
>  *   Gₙ = P2G(Pₙ)
>  *   Solve linear system H⋅dG = -f(Gₙ)
> ```

Think more clearly about what Gn, f, and H are.
___
*[`multibody/mpm/mpm_transfer.h` line 56 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrI2GREqIPY2vi1wR3:-NkrI2GREqIPY2vi1wR4:b-kuwz6i) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/mpm_transfer.h#L56)):*
> ```objc
>  * Output Gₙ₊₁:=Gₙ, Pₙ₊₁:=Pₙ.
>  *
>  * In code, preparing for transfer by calling
> ```

nit you can combine this with the pseudocode above

```
mpm_transfer.SetupTransfer(&sparse_grid, &particles);
while |dG|>ε:
   mpm_transfer.P2G(particles, grid, &grid_data)  //Performing P2G: Gₙ = P2G(Pₙ) 
   // Solve linear system H⋅dG = -f(Gₙ)
   ...
   // Update grid state:  Gₙ = Gₙ + dG
   grid_data blah blah...
   ...
```
  
___
*[`multibody/mpm/mpm_transfer.h` line 108 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrIvlBBXVowARWn6CV:-NkrIvlBBXVowARWn6CW:bdvgl0f) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/mpm_transfer.h#L108)):*
> ```objc
>    * TODO(zeshunzong): finish return mapping and stress computation
>    */
>   void UpdateParticlesVelocityBMatrixDeformationGradientStress(
> ```

nit as much as I like explicit function names, this is getting a little crazy. How about just `UpdateParticleState`?



_Code quote:_
```objc
UpdateParticlesVelocityBMatrixDeformationGradientStress
```
___
*[`multibody/mpm/mpm_transfer.cc` line 25 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrJnZLCH6d-JVjUxDG:-NkrJnZLCH6d-JVjUxDH:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/mpm_transfer.cc#L25)):*
> ```cpp
>                          const GridData<T>& grid_data,
>                          const Particles<T>& particles,
>                          ParticlesData<T>* particles_data) {
> ```

nit



_Suggestion:_
```cpp
particle_data
```
___
*[`multibody/mpm/mpm_transfer.cc` line 53 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrJhg5DPcpwnfALTOC:-NkrJhg66i2_EhFWe5Ad:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/mpm_transfer.cc#L53)):*
> ```cpp
>       }
>     }
>     // write particle v, B, and grad v to scratch
> ```

nit



_Suggestion:_
```cpp
`particle_data`.
```
___
*[`multibody/mpm/particles_data.h` line 18 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrJs0kBK6IvSL64u7V:-NkrJs0l6f0p2W4yRamX:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/particles_data.h#L18)):*
> ```objc
>  */
> template <typename T>
> struct ParticlesData {
> ```

nit



_Suggestion:_
```objc
struct ParticleData
```

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/26)* status: 8 of 14 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/mpm_transfer.h` line 48 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrGahN0Dh-y0IBVQP9:-Nkraf0-AkIEKKahWkD9:b-896fix) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/mpm_transfer.h#L48)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Think more clearly about what Gn, f, and H are.
</blockquote></details>

Done.
___
*[`multibody/mpm/mpm_transfer.h` line 108 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrIvlBBXVowARWn6CV:-NkrOqVi5hGGhzFYwmMl:bev87ez) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/mpm_transfer.h#L108)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit as much as I like explicit function names, this is getting a little crazy. How about just `UpdateParticleState`?
</blockquote></details>

done Per above, UpdateParticlesState, as you are updating the "Particles<T>"
___
*[`multibody/mpm/mpm_transfer.cc` line 25 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrJnZLCH6d-JVjUxDG:-NkrNU4gA7I-LHw1wE7f:b-9091b2) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/mpm_transfer.cc#L25)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

Pass on this
Grid <-> GridData
Particles <-> ParticlesData

I have never used 's anywhere in this code base, so should be fairly clear and consistent.
___
*[`multibody/mpm/mpm_transfer.cc` line 53 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrJhg5DPcpwnfALTOC:-NkrNTBJ5Vm-iBIq6tWJ:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/mpm_transfer.cc#L53)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

done
___
*[`multibody/mpm/particles_data.h` line 18 at r5](https://reviewable.io/reviews/zeshunzong/drake/26#-NkrJs0kBK6IvSL64u7V:-NkrOn1O1H_-Oo_YR9SQ:b-yf860q) ([raw file](https://github.com/zeshunzong/drake/blob/a62bc0993ef5e18356397709bf57583a2afdad64/multibody/mpm/particles_data.h#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

pass see above

**Review by xuchen-han — APPROVED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/26)* status: all files reviewed, 1 unresolved discussion (waiting on @zeshunzong)

**Review by xuchen-han — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

**Pull request merged**
