### PR TITLE
add doc for derivatives of stvkhencky-vonMises model

### PR DESCRIPTION
**Pull request by zeshunzong**
This change is [Reviewable](https://reviewable.io/reviews/zeshunzong/drake/11)

### CODE REVIEW

**Comment by zeshunzong** [comment]
+@xuchenhan-tri

**Review by xuchen-han — CHANGES_REQUESTED** [review]
What's the best way to view this document? The github's default markdown preview doesn't render very nicely.


> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/11#-:-NgVLkyvEIzbulK9ktbA:b-b4m14)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by zeshunzong** [comment]
I do control+shift+v in VScode, should automatically render markdown

**Review by xuchen-han — CHANGES_REQUESTED** [review]
TIL, thanks!

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/11#-:-NgVMhvP6xzn-uPJHPs-:b4m8pki)* status: 0 of 1 files reviewed, all discussions resolved

**Review by xuchen-han — APPROVED** [review]
:lgtm: with a few minor comments. Very nice!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/11#-:-NgVZLJW4zpLAeMwN3rD:bnnuwhp)* status: all files reviewed, 5 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md` line 1 at r1](https://reviewable.io/reviews/zeshunzong/drake/11#-NgVMuYcAn6daXBedGdL:-NgVMuYcAn6daXBedGdM:bhewohy) ([raw file](https://github.com/zeshunzong/drake/blob/2a5587172df3ebe02ebb11740b046eddabb61c65/multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md#L1)):*
> ```Markdown
> How return mapping should be performed has already been documented. Here we derive the derivative relationships.
> ```

Where? Can you provide a reference?



_Code quote:_
```Markdown
How return mapping should be performed has already been documented
```
___
*[`multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md` line 3 at r1](https://reviewable.io/reviews/zeshunzong/drake/11#-NgVMzY1AJ-q49mgVXfR:-NgVMzY1AJ-q49mgVXfS:bb7phvt) ([raw file](https://github.com/zeshunzong/drake/blob/2a5587172df3ebe02ebb11740b046eddabb61c65/multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md#L3)):*
> ```Markdown
> How return mapping should be performed has already been documented. Here we derive the derivative relationships.
> 
> Below we denote $F$ as the deformation gradient *after* return mapping, i,e, the *.
> ```

typo



_Code quote:_
```Markdown
i,e, the *.
```
___
*[`multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md` line 17 at r1](https://reviewable.io/reviews/zeshunzong/drake/11#-NgVXAoB2-bbE6qG8O_M:-NgVXAoB2-bbE6qG8O_N:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/2a5587172df3ebe02ebb11740b046eddabb61c65/multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md#L17)):*
> ```Markdown
> $$
> First Piola Stress is $\frac{d\psi}{dF}.$
> $$P =\frac{d\psi}{dF}= U \frac{d\psi}{d\Sigma} V^T.$$
> ```

nit



_Suggestion:_
```Markdown
$$P =\frac{d\psi}{dF}= U \frac{d \hat\psi}{d\Sigma} V^T.$$
```
___
*[`multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md` line 20 at r1](https://reviewable.io/reviews/zeshunzong/drake/11#-NgVXWTt3cXHbvihUfY-:-NgVXWTt3cXHbvihUfY0:undefined) ([raw file](https://github.com/zeshunzong/drake/blob/2a5587172df3ebe02ebb11740b046eddabb61c65/multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md#L20)):*
> ```Markdown
> $$
> \begin{aligned}
> \frac{\partial \psi}{\partial \sigma_i} & =\frac{1}{\sigma_i}\left[2 \mu\left(\log \sigma_i\right)+\lambda\left(\log \sigma_0+\log \sigma_1+\log \sigma_2\right)\right] \\
> ```





_Suggestion:_
```Markdown
\frac{\partial \hat\psi}{\partial \sigma_i} & =\frac{1}{\sigma_i}\left[2 \mu\left(\log \sigma_i\right)+\lambda\left(\log \sigma_0+\log \sigma_1+\log \sigma_2\right)\right] \\
```
___
*[`multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md` line 21 at r1](https://reviewable.io/reviews/zeshunzong/drake/11#-NgVNMTeB9arOmZH2XLh:-NgVNMTf-uLi2FZXvRGD:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/2a5587172df3ebe02ebb11740b046eddabb61c65/multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md#L21)):*
> ```Markdown
> \begin{aligned}
> \frac{\partial \psi}{\partial \sigma_i} & =\frac{1}{\sigma_i}\left[2 \mu\left(\log \sigma_i\right)+\lambda\left(\log \sigma_0+\log \sigma_1+\log \sigma_2\right)\right] \\
> & =\Sigma^{-1}[2 \mu(\log \Sigma)+\operatorname{trace}(\log \Sigma)].
> ```

nit



_Suggestion:_
```Markdown
& =\Sigma^{-1}[2 \mu(\log \Sigma)+ \lambda\operatorname{tr}(\log \Sigma)].
```

**Review by xuchen-han — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/11)* status: all files reviewed, 6 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md` line 81 at r1](https://reviewable.io/reviews/zeshunzong/drake/11#-NgVZRLr0Xvk7F32IVCV:-NgVZRLr0Xvk7F32IVCW:b-tk0d2u) ([raw file](https://github.com/zeshunzong/drake/blob/2a5587172df3ebe02ebb11740b046eddabb61c65/multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md#L81)):*
> ```Markdown
> In implementation we write `ij=3*j+i` and `rs=3*s+r`, so that the fourth-order tensor is reshaped to a 9by9 matrix.
> ```

nit eliminate unused white spaces.

**Review by zeshunzong — COMMENTED** [review]
All typos fixed. References added.

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/11#-:-NgW5x9HBk8MSy-9WtMX:b-qxbhuz)* status: all files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md` line 1 at r1](https://reviewable.io/reviews/zeshunzong/drake/11#-NgVMuYcAn6daXBedGdL:-NgW4LtaD_z8IadN64qR:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/2a5587172df3ebe02ebb11740b046eddabb61c65/multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md#L1)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Where? Can you provide a reference?
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md` line 3 at r1](https://reviewable.io/reviews/zeshunzong/drake/11#-NgVMzY1AJ-q49mgVXfR:-NgW4OtX0AfXmq-rkcSW:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/2a5587172df3ebe02ebb11740b046eddabb61c65/multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md#L3)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md` line 17 at r1](https://reviewable.io/reviews/zeshunzong/drake/11#-NgVXAoB2-bbE6qG8O_M:-NgW4_Z60DkatqYguV-m:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/2a5587172df3ebe02ebb11740b046eddabb61c65/multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md` line 20 at r1](https://reviewable.io/reviews/zeshunzong/drake/11#-NgVXWTt3cXHbvihUfY-:-NgW4awXB26em9meC1Af:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/2a5587172df3ebe02ebb11740b046eddabb61c65/multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md#L20)):*
> ```Markdown
> $$
> \begin{aligned}
> \frac{\partial \psi}{\partial \sigma_i} & =\frac{1}{\sigma_i}\left[2 \mu\left(\log \sigma_i\right)+\lambda\left(\log \sigma_0+\log \sigma_1+\log \sigma_2\right)\right] \\
> ```

done
___
*[`multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md` line 21 at r1](https://reviewable.io/reviews/zeshunzong/drake/11#-NgVNMTeB9arOmZH2XLh:-NgW4gtw2dS4cNstVqV3:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/2a5587172df3ebe02ebb11740b046eddabb61c65/multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md#L21)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md` line 81 at r1](https://reviewable.io/reviews/zeshunzong/drake/11#-NgVZRLr0Xvk7F32IVCV:-NgW4ocF2JLgYBP7UZ0H:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/2a5587172df3ebe02ebb11740b046eddabb61c65/multibody/mpm/constitutive_model/doc/derivatives_of_stvkhencky_w_vonMises_model.md#L81)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit eliminate unused white spaces.
</blockquote></details>

done

**Review by xuchen-han — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

**Pull request merged**
