### PR TITLE
add sparse grid

### PR DESCRIPTION
**Pull request by zeshunzong**
This change is [Reviewable](https://reviewable.io/reviews/zeshunzong/drake/24)

### CODE REVIEW

**Review by zeshunzong — COMMENTED** [review]
+@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/24#-:-Njk8MDw0L1Ji5CiTqUj:bk7giky)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by xuchen-han — APPROVED** [review]
:lgtm:

Very nice!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/24#-:-NjnCid29Hbep2jfky7R:btmlw2z)* status: all files reviewed, 3 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/sparse_grid.h` line 116 at r1](https://reviewable.io/reviews/zeshunzong/drake/24#-Njn4vZ4ErnP-uu7EY-T:-Njn4vZ4ErnP-uu7EY-U:bv5veti) ([raw file](https://github.com/zeshunzong/drake/blob/c16c40718f58dfa909d89a5479a503ffd5e24f1a/multibody/mpm/sparse_grid.h#L116)):*
> ```objc
>   /// Given a list of base nodes, mark all their neighbors as active nodes, c.f.
>   /// Fig. 3. map_3d_to_1d_ and map_1d_to_3d_ are updated accordingly.
>   void MarkActiveNodes(const std::vector<Vector3<int>>& base_nodes);
> ```

The doc should make clear that a node is considered active **iff** it's a neighbor of at least one node in `base_nodes`. i.e. All previously active nodes that are not neighbor to any nodes in `base_nodes` are no longer considered active.
___
*[`multibody/mpm/sparse_grid.h` line 138 at r1](https://reviewable.io/reviews/zeshunzong/drake/24#-NjnC5KZ2Uo0d2qh9Rr4:-NjnC5KZ2Uo0d2qh9Rr5:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/c16c40718f58dfa909d89a5479a503ffd5e24f1a/multibody/mpm/sparse_grid.h#L138)):*
> ```objc
> 
>  private:
>   double h_;
> ```

nit



_Suggestion:_
```objc
double h_{};
```
___
*[`multibody/mpm/sparse_grid.cc` line 36 at r1](https://reviewable.io/reviews/zeshunzong/drake/24#-NjnBIwW-MDmVgpwwikF:-NjnBIwW-MDmVgpwwikG:b-dhu1p3) ([raw file](https://github.com/zeshunzong/drake/blob/c16c40718f58dfa909d89a5479a503ffd5e24f1a/multibody/mpm/sparse_grid.cc#L36)):*
> ```cpp
>             // if this node is not active, mark as active here
>             map_1d_to_3d_.emplace_back(neighbor_node);
>             map_3d_to_1d_[neighbor_node] = count;
> ```

BTW, an implication of this is that the ordering of the 1d grid indices depend heavily on the ordering of `base_nodes`. Are the input `base_nodes` usually sorted for this function?

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/24)* status: all files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/sparse_grid.h` line 116 at r1](https://reviewable.io/reviews/zeshunzong/drake/24#-Njn4vZ4ErnP-uu7EY-T:-Njo-wlm4sEST6GUde3t:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/c16c40718f58dfa909d89a5479a503ffd5e24f1a/multibody/mpm/sparse_grid.h#L116)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The doc should make clear that a node is considered active **iff** it's a neighbor of at least one node in `base_nodes`. i.e. All previously active nodes that are not neighbor to any nodes in `base_nodes` are no longer considered active.
</blockquote></details>

done
___
*[`multibody/mpm/sparse_grid.h` line 138 at r1](https://reviewable.io/reviews/zeshunzong/drake/24#-NjnC5KZ2Uo0d2qh9Rr4:-Njo-y5UADXnta1KsfNM:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/c16c40718f58dfa909d89a5479a503ffd5e24f1a/multibody/mpm/sparse_grid.h#L138)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

done
___
*[`multibody/mpm/sparse_grid.cc` line 36 at r1](https://reviewable.io/reviews/zeshunzong/drake/24#-NjnBIwW-MDmVgpwwikF:-Njo0-8622MQOAytABAS:bucsnfi) ([raw file](https://github.com/zeshunzong/drake/blob/c16c40718f58dfa909d89a5479a503ffd5e24f1a/multibody/mpm/sparse_grid.cc#L36)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, an implication of this is that the ordering of the 1d grid indices depend heavily on the ordering of `base_nodes`. Are the input `base_nodes` usually sorted for this function?
</blockquote></details>

my design (when you see the whole picture later) is that base nodes are ordered lexicographically. But still, given the current implementation, this does not mean that all the active nodes are ordered lexicographically.

**Review by xuchen-han — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

___
*[`multibody/mpm/sparse_grid.cc` line 36 at r1](https://reviewable.io/reviews/zeshunzong/drake/24#-NjnBIwW-MDmVgpwwikF:-Njo1g-q68_1MxvDetTp:bqrfan2) ([raw file](https://github.com/zeshunzong/drake/blob/c16c40718f58dfa909d89a5479a503ffd5e24f1a/multibody/mpm/sparse_grid.cc#L36)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

my design (when you see the whole picture later) is that base nodes are ordered lexicographically. But still, given the current implementation, this does not mean that all the active nodes are ordered lexicographically.
</blockquote></details>

Understood.

**Review by xuchen-han — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

**Pull request merged**
