### PR TITLE
add corotated model

### PR DESCRIPTION
**Pull request by zeshunzong**
This change is [Reviewable](https://reviewable.io/reviews/zeshunzong/drake/9)

### CODE REVIEW

**Review by zeshunzong — COMMENTED** [review]
+@xuchenhan-tri  Strive to be as careful as I could this time. Decided to not use Doxygen rn until we have a final plan for constitutive models.

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/9#-:-Ng59YHnBhAisXqd1p4u:beic7in)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/9)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/constitutive_model/corotated_elastic_model.h` line 25 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgGAATLARgm_a6sSq9J:-NgGAATLARgm_a6sSq9K:b1zkt9f) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/corotated_elastic_model.h#L25)):*
> ```objc
>   }
> 
>   T CalcStrainEnergyDensity(const Matrix3<T>& FE) const final;
> ```

I am assuming here return T is fine as this is return value optimization, am I correct?

**Review by xuchen-han — CHANGES_REQUESTED** [review]
:lgtm: with some minor comments.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/9#-:-NgKat6g1QahBEUvdYFW:brciwku)* status: all files reviewed, 9 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/constitutive_model/BUILD.bazel` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKMRvGCS57Ffij4wUT:-NgKMRvGCS57Ffij4wUU:bpol7di) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/BUILD.bazel#L11)):*
> ```Starlark
>     "@drake//tools/vector_gen:vector_gen.bzl",
>     "drake_cc_vector_gen_library",
> )
> ```

nit not used



_Code quote:_
```Starlark
load(
    "@drake//tools/vector_gen:vector_gen.bzl",
    "drake_cc_vector_gen_library",
)
```
___
*[`multibody/mpm/constitutive_model/corotated_elastic_model.h` line 18 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKZpGg8f_eJHOLUKhM:-NgKZpGg8f_eJHOLUKhN:bmw9pf3) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/corotated_elastic_model.h#L18)):*
> ```objc
> class CorotatedElasticModel : public ElastoPlasticModel<T> {
>  public:
>   explicit CorotatedElasticModel(const T& youngs_modulus,
> ```

nit not needed since you have a two parameter constructor here.



_Code quote:_
```objc
explicit 
```
___
*[`multibody/mpm/constitutive_model/corotated_elastic_model.h` line 25 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgGAATLARgm_a6sSq9J:-NgKZICe5-lsEKjDuZaf:btrtsva) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/corotated_elastic_model.h#L25)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

I am assuming here return T is fine as this is return value optimization, am I correct?
</blockquote></details>

I'm not sure what you are trying to get at with the question. What's the alternative you have in mind? You can also return by output parameter to avoid allocation in the case T = AutoDiffXd. But since our only use of autodiff is in unit tests, the cost of allocation is not really a point of concern.
___
*[`multibody/mpm/constitutive_model/corotated_elastic_model.cc` line 17 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKZzxA5W51IBiXbEDj:-NgKZzxA5W51IBiXbEDk:bqadtgw) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/corotated_elastic_model.cc#L17)):*
> ```cpp
>     const Matrix3<T>& FE) const {
>   Eigen::JacobiSVD<Matrix3<T>> svd(FE,
>                                    Eigen::ComputeFullU | Eigen::ComputeFullV);
> ```

nit, why do you need the full U and V for the svd?



_Code quote:_
```cpp
Eigen::ComputeFullU
```
___
*[`multibody/mpm/constitutive_model/elastoplastic_model.h` line 29 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKMq-E1PK42zE31jaV:-NgKMq-E1PK42zE31jaW:bp4aeo) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/elastoplastic_model.h#L29)):*
> ```objc
> 
>   // Resets youngs_modulus and updates mu and lambda accordingly, keeping
>   // current poissons_ratio. To help with fracture only.
> ```

nit suggestion



_Suggestion:_
```objc
  // Resets youngs_modulus and updates mu and lambda accordingly, keeping
  // current poissons_ratio.
```
___
*[`multibody/mpm/constitutive_model/elastoplastic_model.h` line 62 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKNOVM00UpGckEhkOs:-NgKNOVM00UpGckEhkOt:b-2ig5v1) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/elastoplastic_model.h#L62)):*
> ```objc
>   // Calculates the Kirchhoff stress τ. FE is the ELASTIC deformation gradient.
>   // Note: P = τ * FE^{-T}, where P is first Piola stress. See
>   // CalcFirstPiolaStress().
> ```

nit, consistency. Ditto in the function below.



_Suggestion:_
```objc
  // Calculates the Kirchhoff stress τ. FE is the elastic deformation gradient.
  // Note: P = τ * FE^{-T}, where P is first Piola stress. See
  // CalcFirstPiolaStress().
```
___
*[`multibody/mpm/constitutive_model/elastoplastic_model.h` line 94 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKYSJ_2vxtnQVPcH_T:-NgKYSJa3d_nSWbmpGKT:bnibdqx) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/elastoplastic_model.h#L94)):*
> ```objc
>   // dP₁₁dF₂₃, dP₁₁dF₃₃] Both the numerator (3by3 matrix) and denominator (3by3
>   // matrix) are flattened column-wise. dPᵢⱼ/dFₖₗ = dPdF(i+3*j, k+3*l), assuming
>   // indices are 0,1,2 rather than 1,2,3.
> ```

Using both 0-based indexing and 1-based indexing in here is confusing.



_Code quote:_
```objc
  // dP₁₁dF₂₃, dP₁₁dF₃₃] Both the numerator (3by3 matrix) and denominator (3by3
  // matrix) are flattened column-wise. dPᵢⱼ/dFₖₗ = dPdF(i+3*j, k+3*l), assuming
  // indices are 0,1,2 rather than 1,2,3.
```
___
*[`multibody/mpm/constitutive_model/elastoplastic_model.h` line 102 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKYeiK9VbuEiTcPqaK:-NgKYeiK9VbuEiTcPqaL:b9uedch) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/elastoplastic_model.h#L102)):*
> ```objc
>   // Remove this after MpmTransfer is finished
>   virtual void UpdateDeformationGradientAndCalcKirchhoffStress(
>       Matrix3<T>* tau, Matrix3<T>* elastic_deformation_gradient) const = 0;
> ```

It's unclear to me, from the documentation, why this function needs to exist.



_Code quote:_
```objc
  // Remove this after MpmTransfer is finished
  virtual void UpdateDeformationGradientAndCalcKirchhoffStress(
      Matrix3<T>* tau, Matrix3<T>* elastic_deformation_gradient) const = 0;
```
___
*[`multibody/mpm/constitutive_model/test/corotated_elastic_model_test.cc` line 94 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKaDru7g3rnp9INCRG:-NgKaDru7g3rnp9INCRH:b6p3qtl) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/test/corotated_elastic_model_test.cc#L94)):*
> ```cpp
>   // Sanity check: no plasticity shall be applied
>   // F_trial_1 now is FE_computed, after return mapping
>   EXPECT_TRUE(CompareMatrices(F_trial1, FE_exact, kTolerance));
> ```

nit this is expected to be exact. Ditto for the similar test below.



_Suggestion:_
```cpp
EXPECT_TRUE(CompareMatrices(F_trial1, FE_exact));
```

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/9)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/constitutive_model/BUILD.bazel` line 11 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKMRvGCS57Ffij4wUT:-NgKjW-r02d-HQr6xkSp:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/BUILD.bazel#L11)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit not used
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/corotated_elastic_model.h` line 18 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKZpGg8f_eJHOLUKhM:-NgKjVBI1xcJSoIp11Y8:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/corotated_elastic_model.h#L18)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit not needed since you have a two parameter constructor here.
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/corotated_elastic_model.h` line 25 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgGAATLARgm_a6sSq9J:-NgKj_VH2molDOM1W5sI:b-arb2g3) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/corotated_elastic_model.h#L25)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

I'm not sure what you are trying to get at with the question. What's the alternative you have in mind? You can also return by output parameter to avoid allocation in the case T = AutoDiffXd. But since our only use of autodiff is in unit tests, the cost of allocation is not really a point of concern.
</blockquote></details>

done. agreed.
___
*[`multibody/mpm/constitutive_model/corotated_elastic_model.cc` line 17 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKZzxA5W51IBiXbEDj:-NgKpT4F6pUEh9bZUCMO:b-n6rhrt) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/corotated_elastic_model.cc#L17)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, why do you need the full U and V for the svd?
</blockquote></details>

done removed
___
*[`multibody/mpm/constitutive_model/elastoplastic_model.h` line 29 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKMq-E1PK42zE31jaV:-NgKo6YdBhESqG7mWG8q:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/elastoplastic_model.h#L29)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit suggestion
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/elastoplastic_model.h` line 62 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKNOVM00UpGckEhkOs:-NgKjsHH-Mg14-uagOS7:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/elastoplastic_model.h#L62)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, consistency. Ditto in the function below.
</blockquote></details>

done
___
*[`multibody/mpm/constitutive_model/elastoplastic_model.h` line 94 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKYSJ_2vxtnQVPcH_T:-NgL1Grm2arI6MXYL4mE:bftumo) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/elastoplastic_model.h#L94)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Using both 0-based indexing and 1-based indexing in here is confusing.
</blockquote></details>

Done If we were to set a rule, I would hope that everything is 0-based.  Modified all my parts accordingly.
___
*[`multibody/mpm/constitutive_model/elastoplastic_model.h` line 102 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKYeiK9VbuEiTcPqaK:-NgKkL8EA80bR7jjwppF:b-n6rhrt) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/elastoplastic_model.h#L102)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

It's unclear to me, from the documentation, why this function needs to exist.
</blockquote></details>

done removed
___
*[`multibody/mpm/constitutive_model/test/corotated_elastic_model_test.cc` line 94 at r1](https://reviewable.io/reviews/zeshunzong/drake/9#-NgKaDru7g3rnp9INCRG:-NgKo1-r42LXDqIV9PX_:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/b19389fd9451b60fdd3788814bf87a8952d2649e/multibody/mpm/constitutive_model/test/corotated_elastic_model_test.cc#L94)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit this is expected to be exact. Ditto for the similar test below.
</blockquote></details>

done

**Review by zeshunzong — COMMENTED** [review]
addressed

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/9#-:-NgL2DDe7hPlawzvtGmb:b-1l9ea)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri)

**Review by xuchen-han — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/9#-:-NgLR_zsB7yzfxBgjNdw:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

**Review by xuchen-han — APPROVED** [review]
You need to rebase on master and resolve conflicts before merging. Make sure you squash the PR into a single commit.

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/9#-:-NgLS7uRErzaHwvXruas:b-e2h8kk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

**Comment by xuchen-han** [comment]
Why is this branch deleted but not merged?

**Comment by zeshunzong** [comment]
I think I have already merged it into master

**Comment by xuchen-han** [comment]
I see. You are technically allowed to do this since you are working on your personal branch. But the usual work flow is merge via reviewable. Merging via reviewable makes sure that nothing goes into your master branch without going through proper review. In principle, you should never privately temper with your target branch (master branch in your case).

**Comment by zeshunzong** [comment]
Understood. When I do rebase and squash, do I still need your LGTM to merge?

**Comment by xuchen-han** [comment]
Not necessarily. But I usually give my reviewer another chance to look at the PR if changes are made (e.g. a conflict is resolved) in the rebase.

**Pull request closed without merging**
