### PR TITLE
finish p2g

### PR DESCRIPTION
**Pull request by zeshunzong**
This change is [Reviewable](https://reviewable.io/reviews/zeshunzong/drake/25)

### CODE REVIEW

**Review by zeshunzong — COMMENTED** [review]
+@xuchenhan-tri 

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/25#-:-NkEkNxiBaBH2vcc-9_v:bk7giky)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Review by xuchen-han — CHANGES_REQUESTED** [review]
A few minor comments before I move on to the tests. Looking good! Much cleaner than before.

> Reviewed 8 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/25#-:-NkGpRAX1jfCP7EIijlh:b-xoze00)* status: 8 of 9 files reviewed, 8 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/mpm_transfer.h` line 19 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGkn9DEyFt1iJMuIyB:-NkGkn9DEyFt1iJMuIyC:b43uj1k) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/mpm_transfer.h#L19)):*
> ```objc
> /**
>  * An implementation of MPM's transfer schemes. We follow Section 10.5 in
>  * https://www.math.ucla.edu/~cffjiang/research/mpmcourse/mpmcourse.pdf.
> ```

nit, a note a how to use this class would be useful here. Consider putting down some pseudocode for a typical workflow something along the line of

```
Particles<double> particles;
SparseGrid<double> grid;
MpmTransfer<double> transfer;
// Must set up transfer before doing P2G.
transfer.SetupTransfer(&grid, &particles);
GridData<double> grid_data;
transfer.P2G(particles, grid, &grid_data);
...
transfer.G2P(grid, grid_data, &particles);
```
___
*[`multibody/mpm/mpm_transfer.h` line 41 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGlxJaCD2nbYX21Ubw:-NkGlxJbAnnBaFauoQkD:byjttbb) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/mpm_transfer.h#L41)):*
> ```objc
>    * @note class attribute pads_ is cleared and then used in this computation.
>    * @note calling this function multiple times should still result in a valid
>    * grid_data, representing the aggregate of all particle data.
> ```

nit consider deleting these notes. They aren't very useful. The first is internal implementation that the caller doesn't need to know about. The second is expected behavior.



_Code quote:_
```objc
   * @note class attribute pads_ is cleared and then used in this computation.
   * @note calling this function multiple times should still result in a valid
   * grid_data, representing the aggregate of all particle data.
```
___
*[`multibody/mpm/particles.h` line 87 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGmyLYACbSNW-Lfy_i:-NkGmyLYACbSNW-Lfy_j:b-jwi9nd) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L87)):*
> ```objc
>   /**
>    * Splats kinematic data on particles to pads. Particles residing in the same
>    * batch *i* will have their data splat to the i-th pad.
> ```

nit, the data splat to pads is more than just kinematic data.



_Suggestion:_
```objc
   * Splats particle data to pads. Particles in batch i will have their
   * data splat to the i-th pad.
```
___
*[`multibody/mpm/particles.h` line 88 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGnEuJ0ARqRS0kMRMd:-NkGnEuJ0ARqRS0kMRMe:b-bylnjo) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L88)):*
> ```objc
>    * Splats kinematic data on particles to pads. Particles residing in the same
>    * batch *i* will have their data splat to the i-th pad.
>    * @note pads will be cleared and resized to num_batches().
> ```

BTW, this class mentions the concept of "batches" several times. It'd be nice to have a section in the class doc explaining what batches are and refer to that section whenever you mention the concept of batches in your documentation



_Code quote:_
```objc
pads will be cleared and resized to num_batches().
```
___
*[`multibody/mpm/particles.h` line 90 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGnnoe-inH1ZcsPlVP:-NkGnnoe-inH1ZcsPlVQ:b-n1gydm) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L90)):*
> ```objc
>    * @note pads will be cleared and resized to num_batches().
>    */
>   void SplatToPads(double h, std::vector<Pad<T>>* pads) const;
> ```

nit document preconditions on this class and h.



_Code quote:_
```objc
void SplatToPads(double h, std::vector<Pad<T>>* pads) const;
```
___
*[`multibody/mpm/particles.h` line 294 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGnWTn-SD0Q75R91QO:-NkGnWTn-SD0Q75R91QP:budqy0s) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L294)):*
> ```objc
>    * particles.
>    */
>   internal::MassAndMomentum<T> ComputeTotalMassMomentum() const;
> ```

FYI, this is fine for your own branch, but in general internal names should not appear in non-internal APIs.



_Code quote:_
```objc
internal::MassAndMomentum<T>
```
___
*[`multibody/mpm/particles.cc` line 232 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGoINF5oSEEULKYTAT:-NkGoINF5oSEEULKYTAU:bfcptqk) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.cc#L232)):*
> ```cpp
>         masses_[p] *
>         (positions_[p].cross(velocities_[p]) +
>          internal::ContractionWithLeviCivita<T>(B_matrices_[p].transpose()));
> ```

BTW, I forgot why this is the formula to use for angular momentum. Can you provide an explanation or a reference as an implementation comment?
___
*[`multibody/mpm/sparse_grid.h` line 140 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGoUg8C-5SOxbNdeqw:-NkGoUg8C-5SOxbNdeqx:bqey7nd) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/sparse_grid.h#L140)):*
> ```objc
>   }
> 
>   /// Computes the states on grid by adding all data stored on pads.
> ```

BTW, I noticed that you are using a mix of `///` and `/** */`. Pick one and stick to it.
___
*[`multibody/mpm/sparse_grid.h` line 140 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGoyu41FK9ZZmC-1mp:-NkGoyu41FK9ZZmC-1mq:b-uobuzi) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/sparse_grid.h#L140)):*
> ```objc
>   }
> 
>   /// Computes the states on grid by adding all data stored on pads.
> ```

nit, clarify that old data are cleared before adding (i.e. this is not accumulating to the grid_data).



_Code quote:_
```objc
/// Computes the states on grid by adding all data stored on pads.
```

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/25)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/mpm_transfer.h` line 19 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGkn9DEyFt1iJMuIyB:-NkHCE642-5NzHMpl5xr:b-f7m4cm) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/mpm_transfer.h#L19)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, a note a how to use this class would be useful here. Consider putting down some pseudocode for a typical workflow something along the line of

```
Particles<double> particles;
SparseGrid<double> grid;
MpmTransfer<double> transfer;
// Must set up transfer before doing P2G.
transfer.SetupTransfer(&grid, &particles);
GridData<double> grid_data;
transfer.P2G(particles, grid, &grid_data);
...
transfer.G2P(grid, grid_data, &particles);
```
</blockquote></details>

done at least partially as of right now
___
*[`multibody/mpm/mpm_transfer.h` line 41 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGlxJaCD2nbYX21Ubw:-NkH1301DE3ZlWxBA8Vf:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/mpm_transfer.h#L41)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit consider deleting these notes. They aren't very useful. The first is internal implementation that the caller doesn't need to know about. The second is expected behavior.
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 87 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGmyLYACbSNW-Lfy_i:-NkGyVm5Aj9n0jFN7iEP:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L87)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, the data splat to pads is more than just kinematic data.
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 88 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGnEuJ0ARqRS0kMRMd:-NkH9qdX5WAP3Du6vjSf:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L88)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, this class mentions the concept of "batches" several times. It'd be nice to have a section in the class doc explaining what batches are and refer to that section whenever you mention the concept of batches in your documentation
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 90 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGnnoe-inH1ZcsPlVP:-NkHACGz-URiPOBrRYTp:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L90)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit document preconditions on this class and h.
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 294 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGnWTn-SD0Q75R91QO:-NkGykRg2TFCmME-oo4X:bmcvbiz) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L294)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, this is fine for your own branch, but in general internal names should not appear in non-internal APIs.
</blockquote></details>

acknowledged. i guess this will not be a problem when we move (almost) everything to internal?
___
*[`multibody/mpm/particles.cc` line 232 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGoINF5oSEEULKYTAT:-NkH-mQv-VOR5LHys356:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.cc#L232)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I forgot why this is the formula to use for angular momentum. Can you provide an explanation or a reference as an implementation comment?
</blockquote></details>

done
___
*[`multibody/mpm/sparse_grid.h` line 140 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGoUg8C-5SOxbNdeqw:-NkH0-I-ByJCo0mA4fOG:bz3fg32) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/sparse_grid.h#L140)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, I noticed that you are using a mix of `///` and `/** */`. Pick one and stick to it.
</blockquote></details>

I always ensure that they never mix within one file. I tend to use /**, but for certain grid based stuff, /// better helps with aligning the figures I draw
___
*[`multibody/mpm/sparse_grid.h` line 140 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGoyu41FK9ZZmC-1mp:-NkH2DOH3-Q8LyAXF25p:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/sparse_grid.h#L140)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, clarify that old data are cleared before adding (i.e. this is not accumulating to the grid_data).
</blockquote></details>

done

**Review by xuchen-han — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/25#-:-NkHFNiu4F-xl7jHW6XH:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/particles.h` line 88 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGnEuJ0ARqRS0kMRMd:-NkHE4we3XZk1NcNoPYR:b-m46wom) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L88)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

done
</blockquote></details>

Apparently my intention isn't well-communicated.

I was simply advocating for moving the detailed explanation you wrote for the doc of `base_nodes` to the class documentation and refer to the class documentation for function documentation that uses the concept of batches.
___
*[`multibody/mpm/particles.h` line 90 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGnnoe-inH1ZcsPlVP:-NkHD7-i6GO-Lql9F3oc:buf6t50) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L90)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

done
</blockquote></details>

```
@pre Prepare() is invoked immediately before the call to SpatToPads().
@pre h > 0
```
___
*[`multibody/mpm/particles.h` line 294 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGnWTn-SD0Q75R91QO:-NkHDOBD3bqtEseAcdAd:b2nhswy) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L294)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

acknowledged. i guess this will not be a problem when we move (almost) everything to internal?
</blockquote></details>

Yes
___
*[`multibody/mpm/sparse_grid.h` line 140 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGoUg8C-5SOxbNdeqw:-NkHDXjx63Jg_NKHx6Pi:bdir6ml) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/sparse_grid.h#L140)):*
> for certain grid based stuff, /// better helps with aligning the figures I draw

I don't understand the reasoning here. For sure you could just add spaces for alignment?
___
*[`multibody/mpm/test/mpm_transfer_test.cc` line 3 at r2](https://reviewable.io/reviews/zeshunzong/drake/25#-NkHE_ioB4LMQ0XB1Q-H:-NkHE_ioB4LMQ0XB1Q-I:bduc1kc) ([raw file](https://github.com/zeshunzong/drake/blob/8eca5bbb15ac6c41304607b3f5fbb90f79764b79/multibody/mpm/test/mpm_transfer_test.cc#L3)):*
> ```cpp
> #include "drake/multibody/mpm/mpm_transfer.h"
> 
> #include <random>
> ```

FYI, fine for your own development branch. But the test needs to be deterministic when we try to move it to drake master. One way of doing that is to simply choose arbitrary numbers for your states below.
___
*[`multibody/mpm/test/mpm_transfer_test.cc` line 69 at r2](https://reviewable.io/reviews/zeshunzong/drake/25#-NkHFD7o9Zo9x5DgvQg8:-NkHFD7o9Zo9x5DgvQg9:b-e9urgt) ([raw file](https://github.com/zeshunzong/drake/blob/8eca5bbb15ac6c41304607b3f5fbb90f79764b79/multibody/mpm/test/mpm_transfer_test.cc#L69)):*
> ```cpp
> 
>   mpm_transfer.SetUpTransfer(&grid, &particles);
>   mpm_transfer.P2G(particles, grid, &grid_data);
> ```

nit, should test conservation after the first time p2g is invoked too.
___
*[`multibody/mpm/test/mpm_transfer_test.cc` line 71 at r2](https://reviewable.io/reviews/zeshunzong/drake/25#-NkHFJx-8ZcYsrr_43Dd:-NkHFJx-8ZcYsrr_43De:bb7phvt) ([raw file](https://github.com/zeshunzong/drake/blob/8eca5bbb15ac6c41304607b3f5fbb90f79764b79/multibody/mpm/test/mpm_transfer_test.cc#L71)):*
> ```cpp
>   mpm_transfer.P2G(particles, grid, &grid_data);
> 
>   // note: invoking p2g multiple types should still be valid
> ```

typo



_Suggestion:_
```cpp
// note: invoking p2g multiple times should still be valid.
```

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/25)* status: all files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/particles.h` line 88 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGnEuJ0ARqRS0kMRMd:-NkHKAop5XPgPIbWO6F7:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L88)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Apparently my intention isn't well-communicated.

I was simply advocating for moving the detailed explanation you wrote for the doc of `base_nodes` to the class documentation and refer to the class documentation for function documentation that uses the concept of batches.
</blockquote></details>

done
___
*[`multibody/mpm/particles.h` line 90 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGnnoe-inH1ZcsPlVP:-NkHIA976rU3ndmpYOCI:b-9umvgx) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L90)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

```
@pre Prepare() is invoked immediately before the call to SpatToPads().
@pre h > 0
```
</blockquote></details>

I don't think the word "immediately" is a good one. Afterall, Prepare() is invoked by MpmTransfer.SetupTransfer(), while SplatToPads() is called by P2G(). The "immediately" is not clearly seen by an user. I made slight modification
___
*[`multibody/mpm/sparse_grid.h` line 140 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGoUg8C-5SOxbNdeqw:-NkHHk9T7EknGE3eaT6i:b-kdqeny) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/sparse_grid.h#L140)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

> for certain grid based stuff, /// better helps with aligning the figures I draw

I don't understand the reasoning here. For sure you could just add spaces for alignment?
</blockquote></details>

there was inconvenience when I am writing it due to auto align. Now it is easy to fix. done.
___
*[`multibody/mpm/test/mpm_transfer_test.cc` line 3 at r2](https://reviewable.io/reviews/zeshunzong/drake/25#-NkHE_ioB4LMQ0XB1Q-H:-NkHG720-wmnMSjBcsmB:b6a5n7x) ([raw file](https://github.com/zeshunzong/drake/blob/8eca5bbb15ac6c41304607b3f5fbb90f79764b79/multibody/mpm/test/mpm_transfer_test.cc#L3)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

FYI, fine for your own development branch. But the test needs to be deterministic when we try to move it to drake master. One way of doing that is to simply choose arbitrary numbers for your states below.
</blockquote></details>

acknowledged
___
*[`multibody/mpm/test/mpm_transfer_test.cc` line 69 at r2](https://reviewable.io/reviews/zeshunzong/drake/25#-NkHFD7o9Zo9x5DgvQg8:-NkHJWM2-JinpG1nP7Ua:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/8eca5bbb15ac6c41304607b3f5fbb90f79764b79/multibody/mpm/test/mpm_transfer_test.cc#L69)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit, should test conservation after the first time p2g is invoked too.
</blockquote></details>

done
___
*[`multibody/mpm/test/mpm_transfer_test.cc` line 71 at r2](https://reviewable.io/reviews/zeshunzong/drake/25#-NkHFJx-8ZcYsrr_43Dd:-NkHGBxc8z2uVRKNRP-7:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/8eca5bbb15ac6c41304607b3f5fbb90f79764b79/multibody/mpm/test/mpm_transfer_test.cc#L71)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

typo
</blockquote></details>

done

**Review by xuchen-han — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/25)* status: all files reviewed, 1 unresolved discussion (waiting on @zeshunzong)

___
*[`multibody/mpm/particles.h` line 88 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGnEuJ0ARqRS0kMRMd:-NkHPB8v52WyXeiidczp:b-gbi3fh) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/particles.h#L88)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

done
</blockquote></details>

I don't see the change. Did you forget to push?

**Review by xuchen-han — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/25)* status: all files reviewed, 1 unresolved discussion (waiting on @zeshunzong)

**Review by xuchen-han — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/25)* status: all files reviewed, 1 unresolved discussion (waiting on @zeshunzong)

___
*[`multibody/mpm/sparse_grid.h` line 140 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGoUg8C-5SOxbNdeqw:-NkI2WNtAc8tiS-SUU28:bi6r4eh) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/sparse_grid.h#L140)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

there was inconvenience when I am writing it due to auto align. Now it is easy to fix. done.
</blockquote></details>

BTW, now you have switched from doxygen comment to normal comment. I don't know if that's intended.

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

___
*[`multibody/mpm/sparse_grid.h` line 140 at r1](https://reviewable.io/reviews/zeshunzong/drake/25#-NkGoUg8C-5SOxbNdeqw:-NkI3XYY8N5li9njvUJU:b-s3kdit) ([raw file](https://github.com/zeshunzong/drake/blob/14828b605e4d92498946618492db04e9ee3b138e/multibody/mpm/sparse_grid.h#L140)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, now you have switched from doxygen comment to normal comment. I don't know if that's intended.
</blockquote></details>

typo in my regex. fixed

**Review by xuchen-han — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

**Pull request merged**
