### PR TITLE
add autodiff for clamp and copy/move specifier

### PR DESCRIPTION
**Pull request by zeshunzong**
This change is [Reviewable](https://reviewable.io/reviews/zeshunzong/drake/8)

### CODE REVIEW

**Comment by zeshunzong** [comment]
@xuchenhan-tri

**Review by xuchen-han — CHANGES_REQUESTED** [review]
Please use +@xuchenhan-tri to allow this PR to show up in the correct sections in my inbox.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/8#-:-Ng0etRcB_oLWZPPEjd5:b7lilp5)* status: all files reviewed, 4 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/internal/math_utils.h` line 51 at r1](https://reviewable.io/reviews/zeshunzong/drake/8#-Ng0fC9S9s4QvalVWRg-:-Ng0fC9TDXeA8jtIV_RE:bqajagf) ([raw file](https://github.com/zeshunzong/drake/blob/682760a05276fa6e166d0cf71d5bd7f8b6bfb192/multibody/mpm/internal/math_utils.h#L51)):*
> ```objc
>  * math_utils.md. Its derivative is 0 when x ∈ (−ε,  ε).
>  * @pre eps > 0
>  */
> ```

nit no doxygen comment in internal namespace.

Please also be consistent when using `// ...` vs `/* ... */` in your commenting styles. Either is fine, but it needs to be consistent



_Code quote:_
```objc
/**
 * Prevents x from getting more than eps-close to zero.See accompanied
 * math_utils.md. Its derivative is 0 when x ∈ (−ε,  ε).
 * @pre eps > 0
 */
```
___
*[`multibody/mpm/internal/math_utils.h` line 53 at r1](https://reviewable.io/reviews/zeshunzong/drake/8#-Ng0f_d9-JDO7-lYGACv:-Ng0f_d9-JDO7-lYGACw:bs3fpct) ([raw file](https://github.com/zeshunzong/drake/blob/682760a05276fa6e166d0cf71d5bd7f8b6bfb192/multibody/mpm/internal/math_utils.h#L53)):*
> ```objc
>  */
> template <typename T>
> T ClampToEpsilon(T x, T eps) {
> ```

These seem to be a recurrent themes.

1. Prefer passing by const reference over by value unless you have a good reason to do otherwise.
2. Does `eps` need to be autodiffable?



_Suggestion:_
```objc
T ClampToEpsilon(const T& x, double eps) {
```
___
*[`multibody/mpm/internal/math_utils.h` line 63 at r1](https://reviewable.io/reviews/zeshunzong/drake/8#-Ng0gMjZ3FrIxwFv63c2:-Ng0gMjZ3FrIxwFv63c3:b-1hhzbq) ([raw file](https://github.com/zeshunzong/drake/blob/682760a05276fa6e166d0cf71d5bd7f8b6bfb192/multibody/mpm/internal/math_utils.h#L63)):*
> ```objc
> 
>     } else {
>       return eps;
> ```

The derivatives are wrong here. You threw away the derivative sizes that x is carrying and arbitrarily replaced it with an undefined behavior. You are setting the derivative to have size 1 and are attempting to modify entry 1 (which doesn't exist) of the derivative.



_Suggestion:_
```objc
    if constexpr (std::is_same_v<T, AutoDiffXd>) {
      return AutoDiffXd(eps, VectorXd::Zero(x.derivatives().size());

    } else {
      return eps;
```
___
*[`multibody/mpm/internal/test/math_utils_test.cc` line 75 at r1](https://reviewable.io/reviews/zeshunzong/drake/8#-Ng0iNzS1qDl4tJ-jHY7:-Ng0iNzS1qDl4tJ-jHY8:byvd3f2) ([raw file](https://github.com/zeshunzong/drake/blob/682760a05276fa6e166d0cf71d5bd7f8b6bfb192/multibody/mpm/internal/test/math_utils_test.cc#L75)):*
> ```cpp
> }
> 
> GTEST_TEST(MathUtilsTest, ClampDerivativeTest) {
> ```

This test will fail in address sanitizer or if you change x to have more than one derivative.



_Code quote:_
```cpp
GTEST_TEST(MathUtilsTest, ClampDerivativeTest) {
```

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/8)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/internal/math_utils.h` line 51 at r1](https://reviewable.io/reviews/zeshunzong/drake/8#-Ng0fC9S9s4QvalVWRg-:-Ng0n2Ok49kDO_JgnMjH:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/682760a05276fa6e166d0cf71d5bd7f8b6bfb192/multibody/mpm/internal/math_utils.h#L51)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit no doxygen comment in internal namespace.

Please also be consistent when using `// ...` vs `/* ... */` in your commenting styles. Either is fine, but it needs to be consistent
</blockquote></details>

done
___
*[`multibody/mpm/internal/math_utils.h` line 53 at r1](https://reviewable.io/reviews/zeshunzong/drake/8#-Ng0f_d9-JDO7-lYGACv:-Ng0n3MrEaKvzIJtzZEv:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/682760a05276fa6e166d0cf71d5bd7f8b6bfb192/multibody/mpm/internal/math_utils.h#L53)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

These seem to be a recurrent themes.

1. Prefer passing by const reference over by value unless you have a good reason to do otherwise.
2. Does `eps` need to be autodiffable?
</blockquote></details>

done

**Review by xuchen-han — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/8)* status: all files reviewed, 2 unresolved discussions (waiting on @zeshunzong)

**Review by zeshunzong — COMMENTED** [review]
got it

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/8#-:-NgKxVPn8C1H3wlVzTRw:b-q8jzb0)* status: all files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/internal/math_utils.h` line 63 at r1](https://reviewable.io/reviews/zeshunzong/drake/8#-Ng0gMjZ3FrIxwFv63c2:-NgKsz5K6kELusxzSYA4:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/682760a05276fa6e166d0cf71d5bd7f8b6bfb192/multibody/mpm/internal/math_utils.h#L63)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

The derivatives are wrong here. You threw away the derivative sizes that x is carrying and arbitrarily replaced it with an undefined behavior. You are setting the derivative to have size 1 and are attempting to modify entry 1 (which doesn't exist) of the derivative.
</blockquote></details>

done
___
*[`multibody/mpm/internal/test/math_utils_test.cc` line 75 at r1](https://reviewable.io/reviews/zeshunzong/drake/8#-Ng0iNzS1qDl4tJ-jHY7:-NgKt-CxAQGUPl4ThGWI:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/682760a05276fa6e166d0cf71d5bd7f8b6bfb192/multibody/mpm/internal/test/math_utils_test.cc#L75)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This test will fail in address sanitizer or if you change x to have more than one derivative.
</blockquote></details>

done

**Review by xuchen-han — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zeshunzong)

**Pull request merged**
