### PR TITLE
Add possion disk sampling dependency

### PR DESCRIPTION
**Pull request by xuchen-han**
Closes #13

- - -
This change is [Reviewable](https://reviewable.io/reviews/zeshunzong/drake/14)

### CODE REVIEW

**Review by xuchen-han — COMMENTED** [review]
+@zeshunzong for review.

> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/14#-:-NgUlUqmAkpQ8vRu9VMZ:b-vqodls)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @zeshunzong)

**Review by xuchen-han — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/14)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @zeshunzong)

___
*[`multibody/mpm/internal/poisson_disk.h` line 13 at r1](https://reviewable.io/reviews/zeshunzong/drake/14#-NgUlbpn2Rz2uIvtLl09:-NgUlbpn2Rz2uIvtLl0A:b6j18nm) ([raw file](https://github.com/zeshunzong/drake/blob/7d0e2bf052abf1cc8fe58f729043864be8a6d597/multibody/mpm/internal/poisson_disk.h#L13)):*
> ```objc
> namespace internal {
> 
> std::vector<Vector3<double>> PoissonDiskSampling(
> ```

This function needs some documentation.

**Review by zeshunzong — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/14)* status: all files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/internal/poisson_disk.h` line 13 at r1](https://reviewable.io/reviews/zeshunzong/drake/14#-NgUlbpn2Rz2uIvtLl09:-NgVGojv9PxOxxyPM3SQ:b82o799) ([raw file](https://github.com/zeshunzong/drake/blob/7d0e2bf052abf1cc8fe58f729043864be8a6d597/multibody/mpm/internal/poisson_disk.h#L13)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

This function needs some documentation.
</blockquote></details>

How should I contribute to your branch? Do you want to just copy and paste the following?

Returns a std::vector of point positions in 3D. Those randomly chosen points fill in the bounding box described by [xmin[0], xmax[0]]X[xmin[1], xmax[1]]X[xmin[2], xmax[2]], while maintain a minimum distance of r between each other.

**Review by zeshunzong — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/14)* status: all files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/internal/poisson_disk.h` line 13 at r1](https://reviewable.io/reviews/zeshunzong/drake/14#-NgUlbpn2Rz2uIvtLl09:-NgVINYpDFod8wMo0aXL:bhemwwy) ([raw file](https://github.com/zeshunzong/drake/blob/7d0e2bf052abf1cc8fe58f729043864be8a6d597/multibody/mpm/internal/poisson_disk.h#L13)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

How should I contribute to your branch? Do you want to just copy and paste the following?

Returns a std::vector of point positions in 3D. Those randomly chosen points fill in the bounding box described by [xmin[0], xmax[0]]X[xmin[1], xmax[1]]X[xmin[2], xmax[2]], while maintain a minimum distance of r between each other.
</blockquote></details>

See https://www.cs.ubc.ca/~rbridson/docs/bridson-siggraph07-poissondisk.pdf.

**Comment by xuchen-han** [comment]
*[`multibody/mpm/internal/poisson_disk.h` line 13 at r1](https://reviewable.io/reviews/zeshunzong/drake/14#-NgUlbpn2Rz2uIvtLl09:-NgVLEZb7RfVeTDSnpdo:bn9bmjs) ([raw file](https://github.com/zeshunzong/drake/blob/7d0e2bf052abf1cc8fe58f729043864be8a6d597/multibody/mpm/internal/poisson_disk.h#L13)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

See https://www.cs.ubc.ca/~rbridson/docs/bridson-siggraph07-poissondisk.pdf.
</blockquote></details>

You should be able to push to this branch directly.

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/14)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/internal/poisson_disk.h` line 13 at r1](https://reviewable.io/reviews/zeshunzong/drake/14#-NgUlbpn2Rz2uIvtLl09:-NgW2H3lC6fbMD--qUED:bz79erk) ([raw file](https://github.com/zeshunzong/drake/blob/7d0e2bf052abf1cc8fe58f729043864be8a6d597/multibody/mpm/internal/poisson_disk.h#L13)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

You should be able to push to this branch directly.
</blockquote></details>

Take a look at the comments and see if you allow merging.

**Review by xuchen-han — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/14)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/internal/poisson_disk.h` line 13 at r1](https://reviewable.io/reviews/zeshunzong/drake/14#-NgUlbpn2Rz2uIvtLl09:-NgW4LQGCAXWAvtO6dEd:b-z83rid) ([raw file](https://github.com/zeshunzong/drake/blob/7d0e2bf052abf1cc8fe58f729043864be8a6d597/multibody/mpm/internal/poisson_disk.h#L13)):*
<details><summary><i>Previously, zeshunzong (Zeshun Zong) wrote…</i></summary><blockquote>

Take a look at the comments and see if you allow merging.
</blockquote></details>

Questions:
1. Is this deterministic? i.e. if I call this function with the same arguments over and over again, will I get the same result?
2. How many points does this sample? What's the stopping criterion? Is it "stop when we can't sample another point that's more than r away from all existing points"?
___
*[`multibody/mpm/internal/poisson_disk.h` line 19 at r2](https://reviewable.io/reviews/zeshunzong/drake/14#-NgW3Xxq3lvQFOIGgJMh:-NgW3Xxq3lvQFOIGgJMi:b-5hvhz1) ([raw file](https://github.com/zeshunzong/drake/blob/bc59ce0561af57a5fa9a2e8a1f6f90710ae0a471/multibody/mpm/internal/poisson_disk.h#L19)):*
> ```objc
>  * between each other.
>  * See https://www.cs.ubc.ca/~rbridson/docs/bridson-siggraph07-poissondisk.pdf.
>  */
> ```

nit Here's my take



_Suggestion:_
```objc
/* Samples points in the bounding box 
 [x_min[0], x_max[0]] X [x_min[1], x_max[1]] X [x_min[2], x_max[2]], while
 maintaining a minimum distance of r between each point pair.
 See https://www.cs.ubc.ca/~rbridson/docs/bridson-siggraph07-poissondisk.pdf. 
 @pre x_max[i] > x_min[i] for i = 0, 1, 2.
 @pre r > 0. */
```

**Review by xuchen-han — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/14)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/internal/poisson_disk.h` line 13 at r1](https://reviewable.io/reviews/zeshunzong/drake/14#-NgUlbpn2Rz2uIvtLl09:-NgW4mpZ1p4DCviTxgsN:b-j4onvx) ([raw file](https://github.com/zeshunzong/drake/blob/7d0e2bf052abf1cc8fe58f729043864be8a6d597/multibody/mpm/internal/poisson_disk.h#L13)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

Questions:
1. Is this deterministic? i.e. if I call this function with the same arguments over and over again, will I get the same result?
2. How many points does this sample? What's the stopping criterion? Is it "stop when we can't sample another point that's more than r away from all existing points"?
</blockquote></details>

You also need a unit test for this function.

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/14)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @xuchenhan-tri)

___
*[`multibody/mpm/internal/poisson_disk.h` line 13 at r1](https://reviewable.io/reviews/zeshunzong/drake/14#-NgUlbpn2Rz2uIvtLl09:-NgWGUrX1fKjzi2c8TZ6:b6s1cuy) ([raw file](https://github.com/zeshunzong/drake/blob/7d0e2bf052abf1cc8fe58f729043864be8a6d597/multibody/mpm/internal/poisson_disk.h#L13)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

You also need a unit test for this function.
</blockquote></details>

Comments edited. Test added.

**Review by xuchen-han — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/14)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @zeshunzong)

___
*[`multibody/mpm/internal/test/poisson_disk_test.cc` line 23 at r3](https://reviewable.io/reviews/zeshunzong/drake/14#-NgWJt2X4TwqdFGBhSz2:-NgWJt2X4TwqdFGBhSz3:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/33b81a095f1080f1162c45d4fc7397dcb330900e/multibody/mpm/internal/test/poisson_disk_test.cc#L23)):*
> ```cpp
>   auto result = PoissonDiskSampling(r, x_min, x_max);
> 
>   // redius is larger than diagonal of bounding box, should return only one
> ```

nit



_Suggestion:_
```cpp
 // radius is larger than diagonal of bounding box, should return only one
```
___
*[`multibody/mpm/internal/test/poisson_disk_test.cc` line 44 at r3](https://reviewable.io/reviews/zeshunzong/drake/14#-NgWK6UmEJp60q3rtZcm:-NgWK6UmEJp60q3rtZcn:bo3983p) ([raw file](https://github.com/zeshunzong/drake/blob/33b81a095f1080f1162c45d4fc7397dcb330900e/multibody/mpm/internal/test/poisson_disk_test.cc#L44)):*
> ```cpp
> 
>   auto result = PoissonDiskSampling(r, x_min, x_max);
> ```

BTW, it'd be nice to test that the number of results here is larger than 1 so that we know the distance tests below are actually in effect.
___
*[`multibody/mpm/internal/test/poisson_disk_test.cc` line 67 at r3](https://reviewable.io/reviews/zeshunzong/drake/14#-NgWKIuG0ocxMfY8DHkM:-NgWKIuG0ocxMfY8DHkN:b2ni8l0) ([raw file](https://github.com/zeshunzong/drake/blob/33b81a095f1080f1162c45d4fc7397dcb330900e/multibody/mpm/internal/test/poisson_disk_test.cc#L67)):*
> ```cpp
>       }
>     }
>   }
> ```

nit



_Suggestion:_
```cpp
  for (size_t i = 0; i < result.size(); ++i) {
    for (size_t j = i+1; j < result.size(); ++j) {
        double distance_sq =
            (result[i](0) - result[j](0)) * (result[i](0) - result[j](0)) +
            (result[i](1) - result[j](1)) * (result[i](1) - result[j](1)) +
            (result[i](2) - result[j](2)) * (result[i](2) - result[j](2));
        EXPECT_TRUE(distance_sq >= r * r);
    }
  }
```

**Review by zeshunzong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/14)* status: 5 of 8 files reviewed, all discussions resolved

___
*[`multibody/mpm/internal/poisson_disk.h` line 19 at r2](https://reviewable.io/reviews/zeshunzong/drake/14#-NgW3Xxq3lvQFOIGgJMh:-NgWMjfm2ljEd2Qk_W_l:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/bc59ce0561af57a5fa9a2e8a1f6f90710ae0a471/multibody/mpm/internal/poisson_disk.h#L19)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit Here's my take
</blockquote></details>

done
___
*[`multibody/mpm/internal/test/poisson_disk_test.cc` line 23 at r3](https://reviewable.io/reviews/zeshunzong/drake/14#-NgWJt2X4TwqdFGBhSz2:-NgWMmMq9J83fdtFhaW-:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/33b81a095f1080f1162c45d4fc7397dcb330900e/multibody/mpm/internal/test/poisson_disk_test.cc#L23)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

done
___
*[`multibody/mpm/internal/test/poisson_disk_test.cc` line 44 at r3](https://reviewable.io/reviews/zeshunzong/drake/14#-NgWK6UmEJp60q3rtZcm:-NgWMnIo423bfL-PeMsf:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/33b81a095f1080f1162c45d4fc7397dcb330900e/multibody/mpm/internal/test/poisson_disk_test.cc#L44)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

BTW, it'd be nice to test that the number of results here is larger than 1 so that we know the distance tests below are actually in effect.
</blockquote></details>

done
___
*[`multibody/mpm/internal/test/poisson_disk_test.cc` line 67 at r3](https://reviewable.io/reviews/zeshunzong/drake/14#-NgWKIuG0ocxMfY8DHkM:-NgWMoMO46dmCczw3CZf:bb7f2mf) ([raw file](https://github.com/zeshunzong/drake/blob/33b81a095f1080f1162c45d4fc7397dcb330900e/multibody/mpm/internal/test/poisson_disk_test.cc#L67)):*
<details><summary><i>Previously, xuchenhan-tri wrote…</i></summary><blockquote>

nit
</blockquote></details>

done

**Review by zeshunzong — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/zeshunzong/drake/14)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @xuchenhan-tri)

**Pull request merged**
